source "https://rubygems.org"

gem "jekyll", "~> 4.0"

gem "minima", "~> 2.0"

group :jekyll_plugins do
  gem "jekyll-asciidoc"
  gem "jekyll-external-links", :path => ".."
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
